backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - name: news
    label: News
    folder: cms/news
    create: true
    fields:
      - { name: "id", label: "Id", widget: "hidden", default: "1"}
      - { name: title, label: Title }
      - { name: "tags", label: "Tags",  widget: "select",
        options: ["Tesla", "Model S", "Model 3", "Model X", "Model Y", "Model Semi", "Roadster", "China", "India",
        "Boring company"]}
      - { name: date, label: Date, widget: "datetime"}
      - { name: tweet, label: tweetId }
      - { name: body, label: Body, widget: markdown }
